column_mappings_torob1 = {
    "fridge_capacity": ["گنجایش یخچال (به لیتر)", "گنجایش یخچال"],
    "freezer_capacity": ["گنجایش فریزر (به لیتر)", "گنجایش فریزر"],
    "total_capacity": ["ظرفیت کل(به لیتر)", "گنجایش کل"],
    "energy_rating": ["نمودار مصرف انرژی", "مصرف انرژی", "رتبه مصرف انرژی"],
    "total_capacity_feet": ["ظرفیت کل(به فوت)", "گنجایش کل به فوت"],
    "number_of_fridge_shelves": ["تعداد طبقات یخچال"],
    "number_of_freezer_shelves": ["تعداد طبقات فریزر"],
    "number_of_fridge_door_shelves": ["تعداد طبقات درب یخچال"],
    "number_of_freezer_door_shelves": ["تعداد طبقات درب فریزر"],
    "number_of_fridge_drawers": ["تعداد کشو یخچال"],
    "number_of_freezer_drawers": ["تعداد کشو فریزر"],
    "no_frost": [
        "بدون برفک",
        "فریزر بدون برفک",
        "یخچال بدون برفک",
        "نوع مقاومت در برابر برفک",
    ],
    "noise_level": ["میزان صدای مزاحم", "میزان صدا", "میزان صدا یخچال"],
    "requires_water_connection": ["لزوم اتصال به شیر آب"],
    "weight": ["وزن", "وزن کل(به کیلو گرم)"],
    "model_code": ["model_code"],
    "price": ["price"],
}

column_mappings_torob2 = {
    "fridge_capacity": [
        "گنجایش یخچال (به لیتر)",
        "گنجایش یخچال",
        "ظرفیت یخچال (لیتر)",
        "ظرفیت خالص یخچال",
    ],
    "freezer_capacity": [
        "گنجایش فریزر (به لیتر)",
        "گنجایش فریزر",
        "گنجایش فریز",
        "ظرفیت فریزر (لیتر)",
        "ظرفیت خالص فریزر",
    ],
    "total_capacity": [
        "ظرفیت کل(به لیتر)",
        "گنجایش کل",
        "گنجایش کل به لیتر",
        "گنجایش کل(به لیتر)",
        "ظرفیت کل (لیتر)",
        "ظرفیت کل خالص (لیتر)",
        "گنجايش کل به ليتر",
    ],

    "energy_rating": [
        "مصرف انرژی",
        "نمودار مصرف انرژی",
        "رتبه انرژی",
        "رده انرژی",
        "کلاس مصرف انرژی",
        "برچسب انرژی",
        "گرید انرژی",
    ],
    "total_capacity_feet": [
        "ظرفیت کل(به فوت)",
        "گنجایش کل به فوت",
        "گنجایش خالص به فوت",
    ],
    "number_of_fridge_shelves": [
        "تعداد طبقات یخچال",
        "تعدادطبقات یخچال",
        "تعداد طبقات داخل درب",
    ],
    "number_of_freezer_shelves": ["تعداد طبقات فریزر", "تعداد طبقات داخل فریزر"],
    "number_of_fridge_door_shelves": [
        "تعداد طبقات درب یخچال",
        "تعداد قفسه های درب یخچال",
        "تعداد پاکت درب یخچال",
    ],
    "number_of_freezer_door_shelves": [
        "تعداد طبقات درب فریزر",
        "تعداد قفسه های درب فریزر",
        "تعداد پاکت درب فریزر",
    ],
    "number_of_fridge_drawers": [
        "تعداد کشو یخچال",
        "تعداد کشوی یخچال",
        "تعداد کشوهای یخچال",
    ],
    "number_of_freezer_drawers": [
        "تعداد کشو فریزر",
        "تعداد کشوی فریزر",
        "تعداد کشوهای فریزر",
    ],
    "no_frost": [
        "بدون برفک",
        "یخچال بدون برفک",
        "فریزر بدون برفک",
        "نوع مقاومت در برابر برفک",
        "نوفراست (بدون برفک)",
        "سیستم بدون برفک (نوفراست)",
        "قابلیت بدون برفک",
    ],
    "noise_level": ["میزان صدای مزاحم", "میزان صدا", "سیستم کاهش صدا در شب"],
    "requires_water_connection": ["لزوم اتصال به شیر آب", "اتصال به آب شهری"],
    "weight": ["وزن کل(به کیلو گرم)", "وزن", "وزن(گرم)", "وزن محصول"],
    "model_code": ["model_code"],
    "price": ["price"]
}

column_mappings_digikala = {
    "fridge_capacity": ["گنجایش یخچال"],
    "freezer_capacity": ["گنجایش فریزر"],
    "total_capacity": ['محدوده گنجایش کل به لیتر'],
    "energy_rating": ["نمودار مصرف انرژی"],
    "total_capacity_feet": ["گنجایش کل به فوت"],
    "number_of_fridge_shelves": ["تعداد طبقات یخچال"],
    "number_of_freezer_shelves": ["تعداد طبقات فریزر"],
    "number_of_fridge_door_shelves": ["تعداد طبقات درب یخچال"],
    "number_of_freezer_door_shelves": ["تعداد طبقات درب فریزر"],
    "number_of_fridge_drawers": ["تعداد کشو"],
    "number_of_freezer_drawers": ["تعداد کشوی فریزر"],
    "no_frost": ["نوع مقاومت در برابر برفک"],
    "noise_level": ["میزان صدا"],
    "requires_water_connection": ["لزوم اتصال به شیر آب"],
    "weight": ["وزن"],
    "model_code": [ "model_code"],
    "price": ["price"]}
